<?php

use Drupal\node\NodeInterface;


function content_translation_workflow_node_presave(NodeInterface $node) {
  $node_storage = \Drupal::entityTypeManager()->getStorage('node');

  // Ensures to sync over translations to never have an unpublished version.
  /** @var \Drupal\node\NodeInterface $original */
  if ($node->getLoadedRevisionId() && ($original = $node_storage->loadRevision($node->getLoadedRevisionId())) && $original->hasTranslation($node->language()->getId())) {
    $original = $original->getTranslation($node->language()->getId());
    if ($node->get('moderation_state')->target_id !== $original->get('moderation_state')->target_id) {
      if ($node->get('moderation_state')->target_id === 'published') {
        foreach ($node->getTranslationLanguages() as $language) {
          $translation = $node->getTranslation($language->getId());
          if ($translation->get('moderation_state')->target_id !== 'published') {
            // When the translation isn't published either, saving the entity
            // would make the translation unpublished. Therefore we have to sync
            // the latest published translation in.

            // First find the latest affected translation, which is published.
            $result = $node_storage->getQuery()
              ->allRevisions()
              ->condition('langcode', $language->getId())
              ->condition('revision_translation_affected', TRUE)
              ->condition('moderation_state.target_id', 'published')
              ->condition('nid', $node->id())
              ->sort('vid', 'DESC')
              ->pager(1)
              ->execute();
            $revision_id = array_keys($result)[0];

            /** @var \Drupal\node\NodeInterface $node_revision */
            $node_revision= $node_storage->loadRevision($revision_id);
            $revision_translation = $node_revision->getTranslation($language->getId());

            $entity_type = $node->getEntityType();
            foreach ($revision_translation as $field_name => $field_item) {
              // These values are not supposed to be changed/copied over.
              if (!in_array($field_name, [$entity_type->getKey('revision'), $entity_type->getKey('id'), $entity_type->getKey('langcode'), $entity_type->getKey('uuid')], TRUE)) {
                /** @var \Drupal\Core\Field\FieldItemListInterface $field_item */
                $translation->set($field_name, $field_item->getValue());
              }
            }
          }
        }
      }
    }
  }

  // 
}

